config/routes.rb
HybridEdu::Application.routes.draw do
  get "printables/letter_tracing"
  get "printables/letters_in_words"
  get "printables/letter_search"
resources :users
resources :sessions, only: [:new, :create, :destroy]  #this is so not all the Restful routes like 'show' and 'edit' dont get passed sense we have no need for them for the sessions (token)

root  'static_pages#home'
match '/signup',     to:	'users#new',							via: 'get'
match '/signin',     to: 'sessions#new',						via: 'get'
match '/signout',    to: 'sessions#destroy',				via: 'delete' #delete here because it destroys the session in order to sign out
match '/games',   	 to: 'static_pages#games',    	via: 'get'
match '/about',   	 to: 'static_pages#about',    	via: 'get'
match '/contact',    to: 'static_pages#contact',    via: 'get'
match '/printables', to: 'static_pages#printables', via: 'get' 
match '/lessons', 	 to: 'static_pages#lessons', via: 'get'
match '/common_core', to: 'static_pages#common_core', via: 'get'
match '/account', to: 'static_pages#account', via: 'get'

match '/lettertrace', 	 to: 	'static_pages#lettertrace', via: 'get'  
match '/letters_in_words', to: 	'static_pages#letters_in_words', via: 'get'

match '/game_letter_search', to: 'static_pages#game_letter_search', via: 'get' 
match '/game_letter_search_2', to: 'static_pages#game_letter_search_2', via: 'get' 
match '/game_letter_search_3', to: 'static_pages#game_letter_search_3', via: 'get' 
match '/game_letter_search_4', to: 'static_pages#game_letter_search_4', via: 'get' 

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def games
  end
	
	def about
	end

	def contact
	end
	
	def printables
	end
	
	def lessons
	end
	
	def common_core
	end
	
	def account
	end
	
	
	def lettertrace
	end
	
	def letters_in_words
	end
	
	def game_letter_search
		@games = true
	end
	
	def game_letter_search_2
		@games = true
	end
	
	def game_letter_search_3
		@games = true
	end
	
	def game_letter_search_4
		@games = true
	end
	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

################################################################	
	
#selects the letter variable to decide which one the kid will be selecting	
	
	def alphabet()
		letter= ('a'..'z').to_a.sample.upcase
		
		letter
	end

#to pick a new letter for the button array, excluding the letter variable
	
	def new_letter(search_letter)
	 	letter= alphabet
	 	
	 	while letter == search_letter do #this only runs when the letter is the same, and it just causes it to pick a new letter..pretty friggen cool
	 		letter= alphabet
		 	end
	 	
	 	return letter
	end

#this is for making the buttons array	 	

 def gay_array(number_of_buttons, search_letter, search_buttons) 
 	array = [ ] 
	
	while array.length <= number_of_buttons - (1 + search_buttons) do
 		array.push(new_letter(search_letter))
 	end
 	
  search_buttons.times do array.push(search_letter)
	end		
 		
 	return array.shuffle
 
 end

#THIS IS a function for the new game

	def letter_maze(button_array,search_letter,dog,house)
		numbers = [6,12]
		
		

					
		for x in numbers do
			button_array.delete_at((dog + x))
			button_array.insert((dog + x), search_letter)
			
			button_array.delete_at((house - x))
			button_array.insert((house - x), search_letter)
		end	
		
		
		 button_array.delete_at(dog)
			button_array.insert(dog, search_letter)
			
		#	button_array.delete_at((dog + 6))
		#	button_array.insert((dog + 6), search_letter)
			
		#	button_array.delete_at((dog + 12))
		#	button_array.insert((dog + 12), search_letter)
			
		#	button_array.delete_at((house - 6))
		#	button_array.insert((house - 6), search_letter)
			
		#	button_array.delete_at((house - 12))
		#	button_array.insert((house - 12), search_letter)

			button_array.delete_at(house)
			button_array.insert(house, search_letter)
			
			if (dog + 12) < (house - 12)
				range = (dog + 12)...(house - 12)
			else
				range = (house - 12)...(dog + 12)
			end
			
			for x in range do
				button_array.delete_at(x)
				button_array.insert( x, search_letter)
				
			
			end
			
			return button_array			
							
	end

#THIS WAS TO SEE IF I COULD GET AN ARRAY OF THE INDEXES OF THE SEARCH LETTERS....and it works
def doggy(array, search_letter)
	search_letter_array= array.each_index.select{|i| array[i] == search_letter}
	return search_letter_array 
end



def correct_btn_id(correct_array, correct_id)
	if correct_id == 1 
		return 1
	elsif correct_id == 2
		return 2
	elsif correct_id == 3 and (correct_array[2]) - (correct_array[1]) == 6	#BUttons that go to the right
		return 3
	elsif correct_id == 4 and (correct_array[2]) - (correct_array[1]) == 6	
		return 4
	elsif correct_id == 5 and (correct_array[2]) - (correct_array[1]) == 6
		return 5
	elsif correct_id == 6 and (correct_array[2]) - (correct_array[1]) == 6 
		return 6
	elsif correct_id == 7 and (correct_array[2]) - (correct_array[1]) == 6 
		return 7			
	elsif correct_id == 8 and (correct_array[2]) - (correct_array[1]) == 6 
		return 8
	elsif correct_id == 9 
		return 9
	elsif correct_id == 10 
		return 10																	
	

	
	

	#this is for any buttons that go to the LEFT of the alignment
	#this is the algaryrhm to figure out what number the button is	
	elsif correct_id == 3 and (correct_array[2]) - (correct_array[1]) < 6 
	 return (((correct_array[1] + 6) - (correct_array[2])) + 3)     
	elsif correct_id == 4 and (correct_array[3]) - (correct_array[2]) < 6 
	 return (((correct_array[1] + 6) - (correct_array[3])) + 3) 
	elsif correct_id == 5 and (correct_array[4]) - (correct_array[2]) < 6 
	 return (((correct_array[1] + 6) - (correct_array[4])) + 3) 
	elsif correct_id == 6 and (correct_array[5]) - (correct_array[2]) < 6 
	 return (((correct_array[1] + 6) - (correct_array[5])) + 3) 
	elsif correct_id == 7 and (correct_array[6]) - (correct_array[2]) < 6 
	 return (((correct_array[1] + 6) - (correct_array[6])) + 3) 
	elsif correct_id == 8 and (correct_array[7]) - (correct_array[2]) < 6 
	 return (((correct_array[1] + 6) - (correct_array[7])) + 3) 

	#these are for the last two buttons going left

	elsif correct_id == 5 and (correct_array[4]) - (correct_array[2]) >= 6
		return correct_id
	elsif correct_id == 6 and (correct_array[5]) - (correct_array[2]) >= 6
		return correct_id
	elsif correct_id == 7 and (correct_array[6]) - (correct_array[2]) >= 6
		return correct_id	
		elsif correct_id == 8 and (correct_array[7]) - (correct_array[2]) >= 6
		return correct_id		

	
	else 
		return 0
	end 

	
end




def button_id(correct_array, array_index)
	if array_index == correct_array[0]
		return 1
	elsif array_index == correct_array[1]
		return 2
	elsif (correct_array[1] + 6 == array_index)
		return 3		
	elsif (array_index == correct_array[2] && (array_index	- correct_array[1]) < 6)
		return (correct_array[1]	+ 6) - (correct_array[2]) + 3
	elsif (array_index == correct_array[] && (array_index	- correct_array[1]) < 6)	
		return (correct_array[1]	+ 6) - (correct_array[2]) + 3
	end
end



################################################################
  #this is to determine id for the star animation
  
  


  def model_id(trigger1,trigger2)
  	if trigger1 == false and letter_trigger2 == false
  		@lt1 = true
  		return "smileModal"
  	elsif letter_trigger1 == true and letter_trigger2 == false
  		@lt2 = true
  		return "smileModal"
		elsif letter_trigger1 == true and letter_trigger2 == true
			return "smileModal"
		end
  end

def level
	
	
	if @level == 1 
		return 'game_letter_search_2'
	elsif @level == 2 #this tells me that this is the first button, then sets the variable as such
		return 'game_letter_search_3' 	
	else 
		nil
  end


end


def starz

	if @lt1 ==  false
		@lt1 = true
		return '#star1'
	elsif @lt2 == false
		@lt2 = true
		return '#star2'
	elsif @lt1 == true and @lt2 == true
		return '#star3'
	else
		nil
	end
	
end


################################################################

# this is to determine which button gets the modal to pop down


end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>



<h1>About Us</h1>
<p>Hybrid Education provides educational resources for Teachers and Parents 
alike.</p>

app/views/static_pages/account.html.erb
<% provide(:title, 'My Account')%>

<h1>My Account</h1>

app/views/static_pages/common_core.html.erb
<% provide(:title, 'Common Core')%>

<h1>Common Core Resources</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact Information</h1>
<p>Chris LaBarge 1-800-cool-guy</p>

<a href="#" class="menu">Hello</a>
<% a = 0 %>

<% while a <= 4  do %>
 	<h1> hey there </h1>
<% a = a + 1%>
<%end	%>

app/views/static_pages/game_letter_search.html.erb
<% provide(:title, 'Letter Search Game') %>
	
<%letter = alphabet%>	
<%@lt1= false%>
<%@lt2= false%>
<%@level = 1%>



<%btn_1 = letter%>
<%btn_2 = new_letter(letter)%>	
<%btn_3 = new_letter(letter)%>	

<%button_array = [btn_1, btn_2, btn_3].shuffle%>

<div class='row' style="height:58px"> <!--this prevents from the rows getting shifted down the page when the star appears-->

	<div class='col-xs-4 center'>
		<%=image_tag("star.png", width:'50', height: '50', id:'star1')%>
	</div>

	<div class='col-xs-4 center'>
		<%=image_tag("star.png", width:'50', height: '50', id:'star2')%>
	</div>
	
	<div class='col-xs-4 center'>
		<%=image_tag("star.png", width:'50', height: '50', id:'star3')%>
	</div>

</div>

<div class='row edu'>	
	<div class='col-xs-12 center' style="margin-top:0px">	
		<h1>Where is <%=letter%> ?</h1>


		<%if button_array[0] == letter%> <!--I dont need the exta script here-->
			<button type="button" class="btn btn-letter btn-circle btn-xl correct" data-toggle="button"><%=button_array[0]%></button>
		
		<%else%> 
			<button type="button" class="btn btn-letter butt btn-circle btn-xl" data-loading-text=<%=button_array[0]%>><%=button_array[0]%></button>
		<%end%> 

		<%if button_array[1] == letter %>
			
			<button type="button" class="btn btn-letter btn-circle btn-xl correct" data-toggle="button"><%=button_array[1]%></button>
	  <%else%>
			<button type="button" class="btn btn-letter butt btn-circle btn-xl" data-loading-text=<%=button_array[1]%>><%=button_array[1]%></button>
		<%end%>

		<%if button_array[2] == letter%>
			
			<button type="button" class="btn btn-letter btn-circle btn-xl correct" data-toggle="button" ><%=button_array[2]%></button>
		<%else%>
			<button type="button" class="btn btn-letter butt btn-circle btn-xl" data-loading-text=<%=button_array[2]%>><%=button_array[2]%></button>
		<%end%>
	</div>
	
 
</div>



	<%=render 'layouts/gamescript'%>

app/views/static_pages/game_letter_search_2.html.erb
<%provide(:title, 'Letter Search Game')%>
<h1> </h1>

<%letter = alphabet%>	
<%@lt1= false%>
<%@lt2= false%>
<%@level= 2%>




<%btn_1= letter%>	
<%btn_2 = letter%>	
<%btn_3 = new_letter(letter)%>	
<%btn_4 = new_letter(letter)%>	
<%btn_5 = new_letter(letter)%>
<%btn_6 = new_letter(letter)%>

<%button_array = [btn_1, btn_2, btn_3, btn_4, btn_5, btn_6].shuffle%>

<div class='row' style="height:58px"> <!--this prevents from the rows getting shifted down the page when the star appears-->

	<div class='col-xs-4 center'>
		<%=image_tag("star.png", width:'50', height: '50', id:'star1')%>
	</div>

	<div class='col-xs-4 center'>
		<%=image_tag("star.png", width:'50', height: '50', id:'star2')%>
	</div>
	
	<div class='col-xs-4 center'>
		<%=image_tag("star.png", width:'50', height: '50', id:'star3')%>
	</div>

</div>

<div class='row edu'>	
	<div class='col-xs-12 center' style="margin-top:0px">	
		<h1>Where is <%=letter%> ?</h1>


		<%if button_array[0] == letter%> <!--I dont need the exta script here-->
			<button type="button" class="btn btn-letter btn-circle btn-xl correct" data-toggle="button"><%=button_array[0]%></button>
		
		<%else%> 
			<button type="button" class="btn btn-letter butt btn-circle btn-xl" data-loading-text=<%=button_array[0]%>><%=button_array[0]%></button>
		<%end%> 

		<%if button_array[1] == letter %>
			
			<button type="button" class="btn btn-letter btn-circle btn-xl correct" data-toggle="button"><%=button_array[1]%></button>
	  <%else%>
			<button type="button" class="btn btn-letter butt btn-circle btn-xl" data-loading-text=<%=button_array[1]%>><%=button_array[1]%></button>
		<%end%>

		<%if button_array[2] == letter%>
			
			<button type="button" class="btn btn-letter btn-circle btn-xl correct" data-toggle="button" ><%=button_array[2]%></button>
		<%else%>
			<button type="button" class="btn btn-letter butt btn-circle btn-xl" data-loading-text=<%=button_array[2]%>><%=button_array[2]%></button>
		<%end%>

		<%if button_array[3] == letter%>
				
			<button type="button" class="btn btn-letter btn-circle btn-xl correct" data-toggle="button"><%=button_array[3]%></button>
		<%else%>
			<button type="button" class="btn btn-letter butt btn-circle btn-xl" data-loading-text=<%=button_array[3]%>><%=button_array[3]%></button>
		<%end%>

		<%if button_array[4] == letter%>
			
			<button type="button" class="btn btn-letter btn-circle btn-xl correct" data-toggle="button"><%=button_array[4]%></button>
		<%else%>
			<button type="button" class="btn btn-letter butt btn-circle btn-xl" data-loading-text=<%=button_array[4]%>><%=button_array[4]%></button>
		<%end%>

		<%if button_array[5] == letter%>
	
			<button type="button" class="btn btn-letter btn-circle btn-xl correct" data-toggle="button"><%=button_array[5]%></button>
		<%else%>
			<button type="button" class="btn btn-letter butt btn-circle btn-xl" data-loading-text=<%=button_array[5]%>><%=button_array[5]%></button>
		<%end%>
		
		
	</div>
	
 
</div>

	<%=render 'layouts/gamescript'%>

app/views/static_pages/game_letter_search_3.html.erb
<%provide(:title, 'Letter Search Game')%>
<h1> </h1>


<%letter = alphabet%>	
<%@lt1= false%>
<%@lt2= false%>
<%@level = 3%>
<%buttons = 9%>
<%array_index = 0%>









<%button_array= [ ]%>
<%button_array = gay_array(buttons, letter, 3)%>




<script>
function lightitup() {
    var x = document.getElementById("muteletters");
    x.style.fontsize = "2.8em";           
    x.style.color = "white"; 
		x.style.textShadow = "rgb(255, 255, 255) 0px 0px 17px"
	
}
</script> 






<div class='row' style="height:58px"> <!--this prevents from the rows getting shifted down the page when the star appears-->

	<div class='col-xs-4 center'>
		<%=image_tag("star.png", width:'50', height: '50', id:'star1')%>
	</div>

	<div class='col-xs-4 center'>
		<%=image_tag("star.png", width:'50', height: '50', id:'star2')%>
	</div>
	
	<div class='col-xs-4 center'>
		<%=image_tag("star.png", width:'50', height: '50', id:'star3')%>
	</div>

</div>

<div class='row edu'>	
	<div class='col-xs-12 center' style="margin-top:0px">	
		<h1>Where is <%=letter%> ?</h1>
	</div>
</div>

<div class='row edu center'>	
	<%while array_index < buttons do %> 	
		<div class= 'col-xs-4' >	
			<div class="button-box">
				<%if button_array[array_index] == letter%> <!--I dont need the exta script here-->
					<button type="button" class="btn btn-letter btn-circle btn-xl correct" data-toggle="button"><%=button_array[array_index]%></button>
				<%else%> 
					<button type="button" class="btn btn-letter butt btn-circle btn-xl" data-loading-text=<%=button_array[array_index]%>><%=button_array[array_index]%></button>
				<%end%> 
			</div>
	 </div>			
 	<%array_index += 1%>
 	<%end%>	 


</div>

	<%=render 'layouts/gamescript'%>

app/views/static_pages/games.html.erb
<% provide(:title, 'Games') %>

<%=link_to('Letter Search Game', game_letter_search_path)%>

app/views/static_pages/home.html.erb
    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->
  

    
    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <div class="circle_first">
          <%=image_tag("worksheets.jpg", width:'180', height: '180', class:'img-circle')%> 
        	</div>
          <h2>Teaching Resources</h2>
          <p>We provide everything from printable worksheets, lesson plans, e-books, and more..all following the Common Core guidelines.</p>
          <p><a class="btn btn-lg btn-green" href="/printables" role="button">View more</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <%=image_tag("girl_tablet.jpg", width:'180', height: '180', class:'img-circle', id:'circle_middle')%> 
          <h2>Interactive Games</h2>
          <p>Everyone of our educational games can be accessed right from our web site. So you don't have have to download any additional apps on your device.  </p>
          <p><a class="btn btn-lg btn-blue" href="#" role="button">View more</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <%=image_tag("kids_tablet.jpg", width:'180', height: '180', class:'img-circle', id:'circle_last')%> 
          <h2>Tools for Educators</h2>
          <p>Subscribed members recieve access to all of our online tools that make your life easier throughout the day.  </p>
          <p><a class="btn btn-lg btn-orange" href="#" role="button">View more</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->
  </div>
	
	
   

app/views/static_pages/lessons.html.erb
<%provide(:title, 'Creative Ideas')%>

<h1>Creative Ideas</h1>

app/views/static_pages/lettertrace.html.erb
<% provide(:title, 'Printable Worksheets')%>

<div class='row printable-row'>
	<!--<div class="col-xs-12 col-sm-7 sheets_div center">
		<%=image_tag('test_sheets.jpg', class:" blog_photo")%>
	</div> -->
	
	<div class="col-xs-12 col-sm-7">
		<div class="sheets_div center">
			<%=image_tag('test_sheets.jpg', class:"blog_photo")%>
		</div>			
		
		<div>
			<h1 style="padding-top:30px;">Letter Search Worksheets</h1>
			<p class="lead"> These are the perfect way to get the little ones recognizing specific letters.
				The font is made to look hand written to allow for an easy transition to print letters.
			</p>
			
			<ul class="lead">
				<li>Capital Letters A-Z</li>
				<li>Lower Case Letters a-z</li>
				<li>Capital & Lowers Case Letters A-z</li>
			</ul>
		</div>
	</div>
	
	<div class="col-xs-12 col-sm-5 ">
		
		<div class="row">
			<div class="  col-xs-10 col-xs-offset-1 col-sm-12 col-sm-offset-0 col-lg-10 col-lg-offset-1">
				<div class="worksheet_div center">
					<%=image_tag("heyitsa.jpg", class:"worksheet")%>
				</div>
			</div>
		</div>		

		
		<div class="row" style="padding-top: 20px;"> <!--this is the goddamn padding for PRINT OR DOWNLOAD-->	
			
			<div class="col-xs-6 col-xs-offset-1">	
				<h2 class="print_download">Print or Download</h2>
			</div>		
			
			<div class="col-xs-4 col-sm-5 col-md-4">
				<%=image_tag('arrow.png',class:'arrow pull-left') %>
			</div>
			
			<div class="col-xs-12">	
				<select class="form-control input-lg select_form" id="dynamic_select">
   	  		<option value="" selected>Select which set of Printables</option>
    			<option value="https://drive.google.com/file/d/0B8TeTx1CN-rpczVYTGVvSVhNNWs/edit?usp=sharing">Upper and Lower Case a-Z</option>
    			<option value="https://drive.google.com/file/d/0B8TeTx1CN-rpd2JWS3ViU292QkE/edit?usp=sharing">Upper Case A-Z</option>
    			<option value="https://drive.google.com/file/d/0B8TeTx1CN-rpRFV4ZHZiWnU5NEE/edit?usp=sharing">Lower Case a-z</option>
				</select>	
			
				<h3 class="center">All sets are<%=image_tag('http://onespiritinterfaith.org/cms/wp-content/uploads/2012/05/pdf-icon-transparent-background2.png', class:"pdf_icon center")%> format</h3>
			</div>	
		
		</div>   	
		
		
	
	
	</div>
	
</div>



<!-- <div class="row"> 
	
	<div class="col-sm-5">
		<div class="row">	
			<div class="col-xs-6">	
				<h2 class="print_download">Print  <sp>or Download</h2>
			</div>		
			<div class="col-xs-5">
				<%=image_tag('arrow.png', height:'50%', width:'50%' ,class:'pull-left') %>
			</div>
		</div>   	
			<select class="form-control input-lg select_form" id="dynamic_select">
   	  	<option value="" selected>Select which set of Printables</option>
    		<option value="https://drive.google.com/file/d/0B8TeTx1CN-rpczVYTGVvSVhNNWs/edit?usp=sharing">Upper and Lower Case a-Z</option>
    		<option value="https://drive.google.com/file/d/0B8TeTx1CN-rpd2JWS3ViU292QkE/edit?usp=sharing">Upper Case A-Z</option>
    		<option value="https://drive.google.com/file/d/0B8TeTx1CN-rpRFV4ZHZiWnU5NEE/edit?usp=sharing">Lower Case a-z</option>
		</select>
	</div> 


</div>

<div class="row">

	<div class="col-xs-10">

		<select class="form-control input-lg" id="dynamic_select">
   	  <option value="" selected>Pick a set of Printables</option>
    	<option value="https://drive.google.com/file/d/0B8TeTx1CN-rpczVYTGVvSVhNNWs/edit?usp=sharing">Upper and Lower Case a-Z</option>
    	<option value="https://drive.google.com/file/d/0B8TeTx1CN-rpd2JWS3ViU292QkE/edit?usp=sharing">Upper Case A-Z</option>
    	<option value="https://drive.google.com/file/d/0B8TeTx1CN-rpRFV4ZHZiWnU5NEE/edit?usp=sharing">Lower Case a-z</option>
		</select>
	</div>
</div> -->

<script>
    $(function(){
      // bind change event to select
      $('#dynamic_select').bind('change', function () {
          var url = $(this).val(); // get selected value
          if (url) { // require a URL
              window.location = url; // redirect
          }
          return false;
      });
    });
</script>


<!--	<%= form_tag() do %>
	<div class="col-lg-4">
			<%= select_tag(:city_id, options_for_select([['Upper and Lower Case a-Z', 1],['Upper Case A-Z', 2],['Lower Case a-z', 3 ]]
			), { :class => 'form-control input-lg"' } ) %>
			
		
	</div>
	<div class="col-lg-2">
		<button type="submit" class="btn btn-primary">View</button>
		<button type="submit" class="btn btn-default">Print</button>

	</div>
<%end%> -->

app/views/static_pages/printables.html.erb
<% provide(:title, 'Printable Material') %>




<div class='row' style="padding-top:20px">
	<div class='col-xs-4 center'>
	<a href='/printables/letter_tracing'><div class='tinty'><%= image_tag('printable_icon.jpg', class:"icon", id:'icon1') %></div></a>
		<h4 class='icon_font'>Letter Tracing</h4>
	</div>
	
	<div class='col-xs-4 center'>
		<a href="/printables/letters_in_words">	<div class='tinty'><%= image_tag('printable_icon2.jpg', class:"icon", id:'icon1') %></div> </a>
		
		<h4 class='icon_font'>Letters in Words</h4>
	</div>
	
	<div class='col-xs-4 center'>
	<a href="/printables/letter_search"><div class="tinty">	<%= image_tag('printable_icon3.jpg', class:"btn btn-gay icon", id:'icon1') %></div></a>
		
		<h4 class='icon_font'>Letter Search</h4>
		
	</div>

</div>



<script>	
	$(document).ready(function(){
		
		$(".icon_font").velocity("transition.slideLeftIn", { stagger: 250 } );
		$(".icon").velocity("transition.slideLeftIn", { stagger: 250 } );
		
	});

</script>