config/routes.rb
HybridEdu::Application.routes.draw do
  get "printables/letter_tracing"
  get "printables/letters_in_words"
  get "printables/letter_search"
resources :users
resources :sessions, only: [:new, :create, :destroy]  #this is so not all the Restful routes like 'show' and 'edit' dont get passed sense we have no need for them for the sessions (token)

root  'static_pages#home'
match '/signup',     to:	'users#new',							via: 'get'
match '/signin',     to: 'sessions#new',						via: 'get'
match '/signout',    to: 'sessions#destroy',				via: 'delete' #delete here because it destroys the session in order to sign out
match '/games',   	 to: 'static_pages#games',    	via: 'get'
match '/about',   	 to: 'static_pages#about',    	via: 'get'
match '/contact',    to: 'static_pages#contact',    via: 'get'
match '/printables', to: 'static_pages#printables', via: 'get' 
match '/lessons', 	 to: 'static_pages#lessons', via: 'get'
match '/common_core', to: 'static_pages#common_core', via: 'get'
match '/account', to: 'static_pages#account', via: 'get'

match '/lettertrace', 	 to: 	'static_pages#lettertrace', via: 'get'  
match '/letters_in_words', to: 	'static_pages#letters_in_words', via: 'get'

match '/game_letter_search', to: 'static_pages#game_letter_search', via: 'get' 
match '/game_letter_search_2', to: 'static_pages#game_letter_search_2', via: 'get' 
match '/game_letter_search_3', to: 'static_pages#game_letter_search_3', via: 'get' 
match '/game_letter_search_4', to: 'static_pages#game_letter_search_4', via: 'get' 

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="/">Hybrid Education</a>
    founded by Chris LaBarge & Jessica Palmieri
  </small>
  <!--<nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact Us", contact_path %></li>
     
    </ul>
  </nav> -->
</footer>

app/views/layouts/_gamescript.html.erb
<!--LOOK UP ON VELOCITY README SEQUENCE RUNNING IN THE TOP OF THE UI PACK README
		THIS IS THE CORRECT WAY TO DO suqunce animation for the dog
-->	
	
	
	<script>
			$(document).ready(function(){
  		
  		  var currentButton = 0
  		  
  		  $(".butt").click(function(){
        	$(this).button('loading').delay(1000).queue(function() {
            $(this).button('reset');
            $(this).dequeue();
        	});        
    		});
  		  
  		 
  	$(".correct").click(function(){
   		 
   		 currentButton = currentButton + 1
   		 
   		 if (currentButton == 1) { 
   		  	
   		  	$("#star1").velocity("transition.bounceRightIn",700 );
  				$("#star1").velocity("callout.shake",600);
  		   
  		    if (<%=@level%> == 1) { 
  		  		setTimeout(function() {
						$('#smileModal').modal('show')
  					$("#smiley").velocity("callout.bounce",1450)
  					}, 1350);	
  		  		
  		    }
  		  
  		  }
  			
		  if (currentButton == 2) {
		  	
		  		$("#star2").velocity("transition.bounceRightIn",700 );
  				$("#star2").velocity("callout.shake",600);
		  	
		  	
		  	  if (<%=@level%> == 2) { 
  		  		setTimeout(function() {
						$('#smileModal').modal('show')
  					$("#smiley").velocity("callout.bounce",1450)
  					}, 1350);	
  		  
  		    }
		  	
		  	
		  	}		
  				
  		
  		if (currentButton == 3) {
		  	
		  		$("#star3").velocity("transition.bounceRightIn",700 );
  				$("#star3").velocity("callout.shake",600);
		  	
		  	  if (<%=@level%> == 3) { 
  		  		setTimeout(function() {
						$('#smileModal').modal('show')
  					$("#smiley").velocity("callout.bounce",1450)
  					}, 1350);	
  		    	
     		
     				
  		    }
		  	
		  	
		  	}		
  		});			
  	
     $("#next").click(function(){
	  	$("#smiley").velocity("callout.bounce",800);
	    
	  setTimeout(function() {
	    window.location.replace("/<%=level%>");
			}, 500);
	  
	  });
    
   
   
   

});
		</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <!-- We use the fluid option here to avoid overriding the fixed width of a normal container within the narrow content columns. -->
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-6">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Hybrid EDU</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-6">
          <ul class="nav navbar-nav ">
            <li><%= link_to "About Us", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li> 
            
            
      <!--    <% if signed_in? %>  
            <li><%= link_to 'Users', users_path %></li>
            <li class="dropdown">
              <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                <li><%= link_to "Profile", current_user %></li>
                 <li><%= link_to "Settings", edit_user_path(current_user) %></li>
             
                <li role="presentation" class="divider"></li>
               <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              </ul>
            </li>
        	<% else %>
						<li><%= link_to "Sign in", signin_path %></li>
					<% end %> -->	        	
          </ul>
        	 <ul class="nav navbar-nav navbar-right center" style="padding-right: 10px;">
    				
    				<li class="li_icon"	id='icon1'> <a href="/printables" class="color_tabs"> <div class='tab_backgroundz' id='green'><%=image_tag('printables.png', height: '60%', width:'60%', class:'nav_icon center')%></div><div class="mobile_menu" id="liteGreen"><p class='p_tag'>Printable Materials</p><p class='lead visible-xs-block'>We offer you a wide selection of printable activities and worksheets</p></div></a></li>
    			 	<li class="li_icon" id='icon2'> <a href="/games" class="color_tabs"> <div class='tab_backgroundz' id='blue' ><%=image_tag('games.png', height: '60%', width:'60%', class:'nav_icon center')%></div> <div class="mobile_menu" id="liteBlue"><p class='p_tag'>Learning Games</p><p class='lead visible-xs-block'>Three NEW! worksheets are available for you to print out...</p></div></a></li>
    				<li class="li_icon"	id='icon3'> <a href='/lessons' class='color_tabs'> <div class='tab_backgroundz' id='purple'><%=image_tag('idea.png', height: '64%', width:'64%', class:'nav_icon')%></div> <div class="mobile_menu" id="litePurple"><p class='p_tag'>Creative Ideas</p></div></a></li>
    				<li class="li_icon" id='icon4'> <a href='/common_core' class='color_tabs'> <div class='tab_backgroundz' id='red'><%=image_tag('apple.png', height: '60%', width:'60%', class:'nav_icon')%></div><div class="mobile_menu" id='liteRed'><p class='p_tag'>Common Core</p></div></a></li>
    				<li class="li_icon" id='icon5'> <a href='/account' class='color_tabs'> <div class='tab_backgroundz' id='orange'><%=image_tag('user.png', height: '60%', width:'60%', class:'nav_icon')%></div><div class="mobile_menu" id='liteOrange'><p class='p_tag'>My Account</p></div></a></li>
    			</ul>
        
        </div><!-- /.navbar-collapse -->
     
      </div>
			
</nav>

<%if heading_select('current_page')%>    
	
	
	<div class='row heading <%=heading_select('class')%>'>
	
		<div class='col-xs-5'>
		
		
		<%=image_tag(heading_select('image'), height: '80px', width:'80px', class:'nav_icon pull-right')%> 
		
	
	</div>
	<div class='col-xs-7' style='height:110px'>	
		<h1 class='heading_font'><%= heading_select('heading')%></h1>
	</div>
</div>

<%end%> 
    

app/views/layouts/_letter_maze.html.erb
<%=%>
	
	<script>
			$(document).ready(function(){
  		
  		  var currentButton = 0
  		  var activeBtn1 = false
  		  var activeBtn2 = false
  		  var activeBtn3 = false
  		  var activeBtn4 = false
  		  var activeBtn5 = false
  		  var activeBtn6 = false
  		  var activeBtn7 = false
				var activeBtn8 = false
				var activeBtn9 = false	
  		  var activeBtn10 = false
  		  
  		 	//This is for making the button red.. i beleive..double check				
  		 
  		  $(".butt").click(function(){
        	$(this).button('loading').delay(1000).queue(function() {
            $(this).button('reset');
            $(this).dequeue();
        	});        
    		});
  		 //---------------------- 
  		 
  	$(".correct").click(function(){
  	
  	//currentButton = currentButton + 1
  	
  	});
  	
  	$("#button_1").click(function(){
   		 
   		activeBtn1 = true
   		
   		currentButton = currentButton + 1 
   		 
   		 if (currentButton == 1) {//<% if @level == 4%>1 <%end%>) { //this shows that i can use ruby wraps in the jquery / jaavascript code 
				   		 
   		 
   		 $("#testies").velocity({
   				 translateZ: 0, // Force HA by animating a 3D property
   				 translateY: "100%",
    				//rotateZ: "45deg" this came with it..for 3d transforms
				}); 	
   		 
   		 } //for this if statement
  		
  		if (currentButton == 2 && activeBtn2 == true) {
  			$("#testies").velocity({
   				 translateZ: 0, // Force HA by animating a 3D property
   				 translateY: "200%",
    				//rotateZ: "45deg" this came with it..for 3d transforms
				}); 	
  			
  		}	
  		
  		if (currentButton == 3) {
  			$("#testies").velocity({
   				 translateZ: 0, // Force HA by animating a 3D property
   				 translateY: "300%",
    				//rotateZ: "45deg" this came with it..for 3d transforms
				}); 	
  			
  		}	
		 
  		}); //end of the the button_1 animation			
			
			$("#button_2").click(function(){
				
				activeBtn2= true
				
				currentButton = currentButton + 1
				
				if (currentButton == 2 && activeBtn3 == false) {
					
					$("#testies").velocity({
   				 translateZ: 0, // Force HA by animating a 3D property
   				 translateY: "200%",
    				//rotateZ: "45deg" this came with it..for 3d transforms
					}); 	
				
		
					
				
				}
				
				
				if (currentButton == 3) {
					
					$("#testies").velocity({
   				 translateZ: 0, // Force HA by animating a 3D property
   				 translateY: "300%",
    				//rotateZ: "45deg" this came with it..for 3d transforms
					}); 	
				
				}
				
				
				
			
			});
			
			$("#button_3").click(function(){
				
				activeBtn3 == true
				
				currentButton = currentButton + 1
				
				if (currentButton == 3) {
					
					$("#testies").velocity({
   				 translateZ: 0, 	// Force HA by animating a 3D property
   				 translateY: "300%",
    				//rotateZ: "45deg" this came with it..for 3d transforms
					}); 	
				
				}
			
			});
			
				$("#button_4").click(function(){
				
				activeBtn4 == true
				
				currentButton = currentButton + 1
				
				if (currentButton == 4) {
					
					
					$("#testies").velocity({
   				 translateZ: 0, // Force HA by animating a 3D property
   			<% if @correct_array[2] - @correct_array[1] == 6%> // going right
   				 translateX: "120%",
    		<% else %>		
    	  	translateX: "-120%",
    	  <% end %>
    				
					}); 	
				
				}
			
			});
			
			
			$("#button_5").click(function(){
				
				activeBtn5 == true
				
				currentButton = currentButton + 1
				
				if (currentButton == 5) {
					
					
					$("#testies").velocity({
   				 translateZ: 0, // Force HA by animating a 3D property
   			<% if @correct_array[2] - @correct_array[1] == 6%> // going right
   				 translateX: "225%",
    		<% else %>		
    	  	translateX: "-225%",
    	  <% end %>
    				
					}); 	
				
				}
			
			});
			
				$("#button_6").click(function(){
				
				activeBtn6 == true
				
				currentButton = currentButton + 1
				
				if (currentButton == 6) {
					
					
					$("#testies").velocity({
   				 translateZ: 0, // Force HA by animating a 3D property
   			<% if @correct_array[2] - @correct_array[1] == 6%> // going right
   				 translateX: "325%",
    		<% else %>		
    	  	translateX: "-325%",
    	  <% end %>
    				
					}); 	
				
				}
			
			});
			
				$("#button_7").click(function(){
				
				activeBtn7 == true
				
				currentButton = currentButton + 1
				
				if (currentButton == 7) {
					
					
					$("#testies").velocity({
   				 translateZ: 0, // Force HA by animating a 3D property
   			<% if @correct_array[2] - @correct_array[1] == 6%> // going right
   				 translateX: "425%",
    		<% else %>		
    	  	translateX: "-425%",
    	  <% end %>
    				
					}); 	
				
				}
			
			});
			
				$("#button_8").click(function(){
				
				activeBtn8 == true
				
				currentButton = currentButton + 1
				
				if (currentButton == 8) {
					
					
					$("#testies").velocity({
   				 translateZ: 0, // Force HA by animating a 3D property   #if it is going right and the button is directly after the last
   			<%=hello_dare(8, @correct_array)%>,
    				
					}); 	
				
				}
			
			});
			
			$("#button_9").click(function(){
				
				activeBtn9 == true
				
				currentButton = currentButton + 1
				
				if (currentButton == 9) {
					
					
					$("#testies").velocity({
   				 translateZ: 0, // Force HA by animating a 3D property
   			
   				 translateY: "400%",
    		
    				
					}); 	
				
				}
			
			});
					$("#button_10").click(function(){
				
				activeBtn10 == true
				
				currentButton = currentButton + 1
				
				if (currentButton == 10) {
					
					
					$("#testies").velocity({
   				 translateZ: 0, // Force HA by animating a 3D property
   			
   				 translateY: "500%",
    		
    				
					}); 	
				
				}
			
			});
			
			
			
			
			
			
				  	
     $("#next").click(function(){
	  	$("#smiley").velocity("callout.bounce",800);
	    
	  setTimeout(function() {
	    window.location.replace("/<%=level%>");
			}, 500);
	  
	  });
    
   
   
   

});
		</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
  <title><%= full_title(yield(:title)) %></title>
  
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <%= stylesheet_link_tag    "application", media: "all",
                                            "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
	
  

</head>
<body class="<%= @games ? 'game-body' : ''%>">

  <!--HOW DOES THIS WORK>!?!?!?!? IT IS AWESOME-->
	 <%= @games ? (nil) : (render 'layouts/header')%>

 	
 	
 	<!-- ################################ TOP OF CARAOSELELEL TESTTTT ###-->
 <% if current_page?('/')%>
 		 <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
         <img src="http://galpod.files.wordpress.com/2013/07/children-learning-with-computer.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Hybrid Education</h1>
              <p> </p>
              <p><a class="btn btn-lg btn-primary" href="/users/new" role="button">Sign up today</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="http://1.bp.blogspot.com/-T2yw9vo6K6Y/Txtg6nCfZyI/AAAAAAAAAr8/JmlwEbFvQdI/s1600/GUGCenters%255B1%255D.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Another example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="/about" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="http://www.cdc.gov/vaccinesafety/images/preschoolers_and_teacher1.JPG" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="/games" role="button">Browse Games</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div><!-- /.carousel -->
	 

	

 	
 	
 	<!-- ################################ BOTTOM OF CARAOSELELEL TESTTTT ###-->
 <%else%>
 	<% nil %>
 <% end %>
	 	<!-- ################################ BOTTOM OF CARAOSELELEL TESTTTT ###-->
	
	
	
	
	<div class='container'>
		<% flash.each do |key, value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key}") %> <!--This is pretty badass, checkout the content_tag function-->
		<% end %>
		<%= yield %>
		
	<!--<%= debug(params) if Rails.env.development? %> -->
	</div>
	
	<% if current_page?('/')%>
			
				
      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="div" id="green">
        <div class="container">
        	<div class="row featurette">
        		<div class="col-md-7">
          		<h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
          		<p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        		</div>
       			
       			<div class="col-md-5">
          		<div class="feature-div">
          			<%= image_tag('teacher_printables.jpg', class:"featurette-image img-responsive")%>
        			</div>
        		</div>
      		
      		</div>
				</div>
			</div>
			
			<div class="div" id="blue">
				<div class="container">	
					<div class="row featurette">
        		<div class="col-md-5">
          		<img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        		</div>
        		
        		<div class="col-md-7">
         		 <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
         		 <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        		</div>
     		  </div>
      	</div>
      </div>
      
      <div class="div" id="purple">
        <div class="container">
        	<div class="row featurette">
        		<div class="col-md-7">
          		<h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
          		<p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        		</div>
       			
       			<div class="col-md-5">
          		<%= image_tag('teacher_printables.jpg', class:"featurette-image img-responsive")%>
        		</div>
      		
      		</div>
				</div>
			</div>
			
			
			
			
			
   
	<%else nil%>
	<%end%>
	
	
	<div class='container'>
		<%= @games ? (nil) : (render 'layouts/footer')%>
	</div>
	
	
    <!-- Bootstrap core JavaScript -->
  <!--  ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  <!--  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> -->
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/docs.min.js"></script>
		
		
		<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="smileModal" data-backdrop="static" >
  <div class="modal-dialog modal-sm">
    <div class="modal-content text-center">
      <%=image_tag("http://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Smiley.svg/1024px-Smiley.svg.png", height:'200px', width:'200px', id:'smiley')%>
    	<button type="button" class="btn btn-primary btn-lg" id="next">Next Level</button>
    </div>
  </div>
</div> 
		
		
		
   



<script>
window.addEventListener('load', function() {
    FastClick.attach(document.body);
}, false);
</script>

	
</body>
</html>